# Generated by Django 4.1.3 on 2022-11-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='child_001.category'),
            preserve_default=False,
        ),
    ]
