# Generated by Django 4.1.3 on 2022-12-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0004_blog_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
