# Generated by Django 4.1.3 on 2023-03-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0005_remove_blog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
