# Generated by Django 4.1.3 on 2023-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_001', '0006_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
